name: CI
on: [push, pull_request]
jobs:
  android-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: v20.1.0
        - name: Install Dependencies
          run: npm ci
        - name: Run test on Android Emulator
          run: npx wdio ./wdio.conf.ts
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs